#mDota plugin configuration file

#Prevent blocks from being modified
PreventBlockModification: true

#Add team colors to tablist
TabListColors: true

#Color the nameplates above the heads of players
NameplateColors: true

#Strip armor from mobs to make the game more fair
StripMobArmor: true

#Put helmets on mobs to prevent them from burning in the sunlight
HelmetOnMobs: true

#Use scoreboard to keep track of scores
UseScoreboard: true

#Should players retain their items on death?
RetainItems: false

#Should players retain their armor on death?
RetainArmor: true

#Should players retain their levels on death?
RetainLevels: false

#Is recall enabled?
EnableRecall: false

#Time until recall
RecallTime: 7

#Max players per game
MaxPlayersPerGame: 12