name: mDota
main: com.mordrum.mdota.mDota SirSavary
version: 0.4
commands:
    dota:
        description: Dota commands
        usage: "/dota [join|restart|score|recall]"
    t:
        description: Team chat
        usage: "/t message"
permissions:
    mdota.restart:
        description: Allows you to restart the game when it is finished
        default: false
    mdota.forcerestart:
        description: Allows you to restart the game at any time
        default: false
    mdota.chooseteam:
        description: Allows you to choose a team to join
        default: false