name: mCommon
main: com.mordrum.mcommon.mCommon
version: 0.6
author: SirSavary
commands:
    ekg:
        description: Server monitor command
        usage: "/ekg"
permissions:
    mcommon.ekg:
        description: Allows you to use /ekg
        default: op